### ISSUE TITLE
Could you add detailed readme to be able to understand more from your code please?

### ISSUE THREAD

**Issue by javaHelper** [anurag-upad/Online-Food-Delivery-System#1]

**Comment by anurag-upad** [comment]
Sure, made the changes in Readme file with REST endpoints and more details.
Thanks!

**Comment by javaHelper** [comment]
Can we add Feign client to call micro services?  Also have a API Gateway, Resilient4J implementation. Thanks!  May be add Security using Keycloak, distributed Config server, ZipKin, Sleuth, Feign for inter-service communication etc.

**Comment by anurag-upad** [comment]
added API gateway for now. will do more.
